title: 6th Klagenfurt Winter Game Jam
date: December 9th to 11th 2022
itchio: https://itch.io/jam/6th-winter-game-jam
registrationUrl: https://itch.io/jam/6th-winter-game-jam
previousitchio: https://itch.io/jam/9th-klujam # no trailing slash!
enddate: December 11th, 4pm CEST
collections:
    sponsors:
        sort_by: gold